spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mumschool?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    userName: mumschool_developer
    password: MumSch@@1
weixin:
  conf:
    appId: wx8ac62c85db9b17f1
    appsecret: a02fa78c745aac5a4716e7db3da968bd
    base_url: http://www.mamxy.com/mumschool/sys/handler
    weixin_token: mummyCathedra
other:
    Access-Control-Allow-Origin-url: http://www.mamxy.com